<script setup>
const props = defineProps({
  currentSlideIndex: Number,
  index: Number,
  ficha: Object,
});

const imagen = `/img/emociones/${props.ficha.nombre}.jpg`;

const isAnimated = computed(() => {
  return props.currentSlideIndex === props.index;
});
</script>
<template>
  <div
    class="wrapper"
    :class="{ 'animate__animated animate__fadeIn': isAnimated }"
  >
    <div class="content">
      <img
        :src="imagen"
        class="emocion-img"
        :class="{ 'animate__animated animate__fadeInDown': isAnimated }"
      />
      <div>
        <div
          class="reaction-banner"
          :class="{ 'animate__animated animate__bounceIn': isAnimated }"
        >
          <div class="reaction-text">REACTIONS GENERATED BY THIS IMAGE</div>
          <div class="reaction-count">
            {{
              parseInt(ficha["reacciones"]).toLocaleString("es-ES", {
                useGrouping: true,
              })
            }}
          </div>
        </div>
        <div class="tarta">
          <img class="tarta-img" src="/img/tarta.png" alt="Tarta" />
          <div class="tarta-caja devotion">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["devotion"] }}</div>
              <div class="tarta-percent">%</div>
            </div>

            <div class="tarta-text">Devotion</div>
          </div>
          <div class="tarta-caja caja-negra longing">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["longing"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Longing</div>
          </div>
          <div class="tarta-caja caja-verde enthusiasm">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["enthusiasm"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Enthusiasm</div>
          </div>
          <div class="tarta-caja surprise">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["surprise"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Surprise</div>
          </div>
          <div class="tarta-caja caja-negra tenderness">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["tenderness"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Tenderness</div>
          </div>
          <div class="tarta-caja fervor">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["fervency"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Fervency</div>
          </div>
          <div class="tarta-caja caja-verde admiration">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["admiration"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Admiration</div>
          </div>
          <div class="tarta-caja caja-negra optimism">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["optimism"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Optimism</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
$verde: #00ce7e;

footer {
  background-color: $verde;
  padding: 3em 1em 1em;
  margin-top: auto;
}

.wrapper {
  //padding: 4em;
  //background: #606060;
}

.content {
  height: calc(100vh);
  background: #000;
  display: flex;
  flex-direction: column;
}

.reaction-banner {
  color: $verde;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-family: "Barlow-SemiBold";
  text-align: center;
  padding: 1em 5em;
  margin-left: 6em;
  margin-right: 6em;
  margin-top: -12em;
}

.reaction-text {
  flex: 1;
  font-size: 2.8em;
  line-height: 1em;
  font-weight: bold;
}

.reaction-count {
  flex: 1;
  text-align: center;
  font-size: 7em;
}

.emocion-img {
  width: 100%;
}

.tarta {
  position: relative;
  display: flex;
  margin-top: 10em;

  .tarta-img {
    margin: auto;
    width: 60%;
  }

  .tarta-caja {
    position: absolute;
    background-color: white;
    height: 280px;
    width: 280px;
    border-radius: 0.3em;
    border: 0.2em solid;
    transform: scale(0.5);
    animation: scaleAA 1.2s linear infinite 0.2s;
  }

  .caja-negra {
    background-color: #000000;
    border-color: $verde;
    color: white;
  }

  .caja-verde {
    background-color: $verde;
  }

  .tarta-caja-superior {
    padding: 0 2em;
    display: flex;
    justify-content: center;
  }

  .tarta-number {
    font-size: 4em;
    text-align: center;
    font-family: Barlow-Black;
    text-transform: uppercase;
  }

  .tarta-percent {
    font-size: 2em;
    margin-top: 0.6em;
    text-align: center;
    font-family: Barlow-Black;
    font-weight: bold;
    text-transform: uppercase;
  }

  .tarta-text {
    font-size: 1.5em;
    text-align: center;
    font-family: Barlow-SemiBold;
    text-transform: uppercase;
  }

  .devotion {
    top: -7em;
    left: 32em;
    animation-delay: 0s;

    //zoom: 0.9;
  }

  .optimism {
    top: -4em;
    left: 20em;
    //zoom: 0.8;
    animation-delay: 0.2s;
  }

  .admiration {
    top: 6em;
    left: 10em;
    //zoom: 0.7;
    animation-delay: 0.4s;
  }

  .fervor {
    top: 18em;
    left: 12em;
    //zoom: 0.6;
    animation-delay: 0.6s;
  }

  .tenderness {
    top: 20em;
    left: 28em;
    //zoom: 0.8;
    animation-delay: 0.8s;
  }

  .surprise {
    top: 17em;
    left: 42em;
    //zoom: 0.5;
    animation-delay: 1s;
  }

  .enthusiasm {
    top: 6em;
    left: 52em;
    //zoom: 0.8;
    animation-delay: 1.2s;
  }

  .longing {
    top: -6em;
    left: 46em;
    animation-delay: 1.2s;
  }
}

.animateScale {
  transform: scale(0.5);
  animation: scaleAA 1.2s linear infinite 0.2s;
}

@keyframes scaleAA {
  0% {
    transform: scale(0.5);
  }
  50% {
    transform: scale(1.1);
  }
  100% {
    transform: scale(1);
  }
}
</style>
