<script setup>
const props = defineProps({
  ficha: Object,
});

const imagen = `/img/emociones/${props.ficha.nombre}.jpg`;
</script>
<template>
  <div class="wrapper">
    <div class="content">
      <img :src="imagen" class="emocion-img" />
      <div>
        <div class="reaction-banner">
          <div class="reaction-text">REACTIONS GENERATED BY THIS IMAGE</div>
          <div class="reaction-count">
            {{ ficha["reacciones"].toLocaleString() }}
          </div>
        </div>
        <div class="tarta">
          <img class="tarta-img" src="/img/tarta.png" alt="Tarta" />
          <div class="tarta-caja devotion">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["devotion"] }}</div>
              <div class="tarta-percent">%</div>
            </div>

            <div class="tarta-text">Devotion</div>
          </div>
          <div class="tarta-caja caja-negra longing">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["longing"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Longing</div>
          </div>
          <div class="tarta-caja caja-negra enthusiasm">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["enthusiasm"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Enthusiasm</div>
          </div>
          <div class="tarta-caja caja-verde surprise">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["surprise"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Surprise</div>
          </div>
          <div class="tarta-caja caja-negra tenderness">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["tenderness"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Tenderness</div>
          </div>
          <div class="tarta-caja caja-negra fervor">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["fervency"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Fervency</div>
          </div>
          <div class="tarta-caja caja-verde admiration">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["admiration"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Admiration</div>
          </div>
          <div class="tarta-caja caja-negra optimism">
            <div class="tarta-caja-superior">
              <div class="tarta-number">{{ ficha["optimism"] }}</div>
              <div class="tarta-percent">%</div>
            </div>
            <div class="tarta-text">Optimism</div>
          </div>
        </div>
      </div>
      <footer>
        <img src="/img/footer.png" alt="Footer" />
      </footer>
    </div>
  </div>
</template>

<style lang="scss" scoped>
$verde: #00ce7e;

footer {
  background-color: $verde;
  padding: 3em 1em 1em;
  margin-top: auto;
}

.wrapper {
  padding: 4em;
  background: #606060;
}

.content {
  height: calc(100vh - 8em);
  background: #000;
  display: flex;
  flex-direction: column;
}

.reaction-banner {
  background-color: $verde;
  color: black;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-family: "Barlow-Black";
  text-align: center;
  padding: 1em;
  margin: 3em;
}

.reaction-text {
  flex: 1;
  font-size: 3.2em;
  line-height: 1em;
  font-weight: bold;
}

.reaction-count {
  flex: 1;
  text-align: center;
  font-size: 8em;
}

.emocion-img {
  height: 46em;
  width: 100%;
}

.tarta {
  position: relative;
  display: flex;
  margin-top: 10em;

  .tarta-img {
    margin: auto;
  }

  .tarta-caja {
    position: absolute;
    background-color: white;
    height: 300px;
    width: 300px;
    border-radius: 0.3em;
    border: 0.2em solid;
  }

  .caja-negra {
    background-color: #000000;
    border-color: $verde;
    color: white;
  }

  .caja-verde {
    background-color: $verde;
  }

  .tarta-caja-superior {
    padding: 0 2em;
    display: flex;
    justify-content: center;
  }

  .tarta-number {
    font-size: 4em;
    text-align: center;
    font-family: Barlow-Black;
    text-transform: uppercase;
  }

  .tarta-percent {
    font-size: 2em;
    margin-top: 0.6em;
    text-align: center;
    font-family: Barlow-Black;
    font-weight: bold;
    text-transform: uppercase;
  }

  .tarta-text {
    font-size: 1.5em;
    text-align: center;
    font-family: Barlow-SemiBold;
    text-transform: uppercase;
  }

  .devotion {
    top: -7em;
    left: 30em;
  }

  .optimism {
    top: -4em;
    left: 15em;
  }

  .admiration {
    top: 8em;
    left: 2em;
  }

  .fervor {
    top: 22em;
    left: 5em;
  }

  .tenderness {
    top: 22em;
    left: 24em;
  }

  .surprise {
    top: 20em;
    left: 40em;
  }

  .enthusiasm {
    top: 8em;
    left: 52em;
  }

  .longing {
    top: -5em;
    left: 45em;
  }
}
</style>
